package com.aima.entity;

import com.aima.enums.ContentLifecycle;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.util.ArrayList;
import java.util.List;

/**
 * Original content generated by the AI from a brand profile + strategy (BR-03).
 * Optionally derived from a {@link ContentIdea}.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "content_items")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class ContentItem extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "brand_profile_id", nullable = false)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    BrandProfile brandProfile;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "content_idea_id")
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    ContentIdea contentIdea;

    @Column(name = "script", columnDefinition = "text")
    String script;

    @Column(name = "caption", columnDefinition = "text")
    String caption;

    @Column(name = "hashtag", columnDefinition = "text")
    String hashtag;

    @Column(name = "cta", length = 255)
    String cta;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    ContentLifecycle status = ContentLifecycle.DRAFT;

    @OneToMany(mappedBy = "contentItem", cascade = CascadeType.ALL, orphanRemoval = true)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    List<ContentVersion> contentVersions = new ArrayList<>();

    @OneToMany(mappedBy = "contentItem", cascade = CascadeType.ALL, orphanRemoval = true)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    List<MediaAsset> mediaAssets = new ArrayList<>();
}
