package com.aima.entity;

import com.aima.enums.ContentLifecycle;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Original content generated by the AI from a brand profile + strategy (BR-03).
 * Optionally derived from a {@link ContentIdea}.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "content_items")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class ContentItem extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "brand_profile_id", nullable = false)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    BrandProfile brandProfile;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "content_idea_id")
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    ContentIdea contentIdea;

    /** Kịch bản quay dạng chuỗi JSON có cấu trúc (hook/steps/cta — xem util/ScriptJson). */
    @Column(name = "script", columnDefinition = "text")
    String script;

    @Column(name = "caption", columnDefinition = "text")
    String caption;

    @Column(name = "hashtag", columnDefinition = "text")
    String hashtag;

    @Column(name = "cta", length = 255)
    String cta;

    @Column(name = "media_prompt", columnDefinition = "text")
    String mediaPrompt;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    ContentLifecycle status = ContentLifecycle.DRAFT;

    // ===== Trạng thái wizard (auto-save để "Tiếp tục" bài dở) — chỉ có nghĩa khi DRAFT,
    // được dọn null khi bài rời DRAFT (PATCH status). =====

    /** Bước wizard đang dừng (1-4). */
    @Column(name = "wizard_step")
    Integer wizardStep;

    /** Nền tảng đã chọn cho bài, CSV tên enum (vd "FACEBOOK,INSTAGRAM"). */
    @Column(name = "wizard_platforms", length = 100)
    String wizardPlatforms;

    /** Ghi chú thêm cho AI nhập ở bước Chọn nguồn. */
    @Column(name = "wizard_note", columnDefinition = "text")
    String wizardNote;

    /** Trend gắn kèm đã chọn (id tham chiếu mềm — resolve nội dung lúc generate). */
    @Column(name = "trend_id")
    UUID trendId;

    @OneToMany(mappedBy = "contentItem", cascade = CascadeType.ALL, orphanRemoval = true)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    List<ContentVersion> contentVersions = new ArrayList<>();

    @OneToMany(mappedBy = "contentItem", cascade = CascadeType.ALL, orphanRemoval = true)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    List<MediaAsset> mediaAssets = new ArrayList<>();
}
