import type { FailedPost } from './api/failedPosts.ts';

// Mock demo cho trang "Bài lỗi & cần xử lý" — dùng khi backend chưa chạy / user chưa có bài lỗi
// (cùng vai trò với trendsData.ts của trang Trends). Dữ liệu thật luôn được ưu tiên.
// Mã lỗi lấy theo Graph API thật: 368 (vi phạm chuẩn cộng đồng), 190 (token hết hạn),
// 4 (rate limit), 100 (sai tham số/media), 2 (lỗi tạm thời phía nền tảng).
// Đủ >10 bản ghi để demo phân trang 10 item/trang của layout master–detail.

const MOCK_FAILED_POSTS: FailedPost[] = [
  {
    id: 'mock-1',
    scheduleId: 'mock-sch-1',
    contentItemId: 'mock-ci-1',
    platformName: 'FACEBOOK',
    accountName: 'AIMA Coffee House',
    caption: 'Giảm 50% toàn bộ menu — nhanh tay kẻo lỡ! Cam kết rẻ nhất thị trường, không đâu bằng.',
    errorType: 'POLICY_VIOLATION',
    errorCode: '368',
    errorMessage: 'Nội dung vi phạm Tiêu chuẩn cộng đồng: quảng cáo phóng đại, tuyên bố tuyệt đối chưa được kiểm chứng.',
    failedAt: '2026-07-13T09:24:00',
  },
  {
    id: 'mock-2',
    scheduleId: 'mock-sch-2',
    contentItemId: 'mock-ci-2',
    platformName: 'INSTAGRAM',
    accountName: '@aima.coffee',
    caption: 'Bí quyết pha cold brew tại nhà chỉ với 3 bước đơn giản ☕',
    errorType: 'PERMANENT',
    errorCode: '190',
    errorMessage: 'Access token đã hết hạn. Hãy kết nối lại tài khoản Instagram để tiếp tục đăng bài.',
    failedAt: '2026-07-13T07:10:00',
  },
  {
    id: 'mock-3',
    scheduleId: 'mock-sch-3',
    contentItemId: 'mock-ci-3',
    platformName: 'THREADS',
    accountName: '@aima.coffee',
    caption: 'Bạn thuộc team cà phê sữa hay team cà phê đen? Comment cho mình biết nhé!',
    errorType: 'TEMPORARY',
    errorCode: '4',
    errorMessage: 'Vượt giới hạn số lần gọi API của nền tảng. Đã thử lại 3 lần nhưng chưa thành công.',
    failedAt: '2026-07-12T20:45:00',
  },
  {
    id: 'mock-4',
    scheduleId: 'mock-sch-4',
    contentItemId: 'mock-ci-4',
    platformName: 'FACEBOOK',
    accountName: 'AIMA Coffee House',
    caption: 'Ảnh hậu trường buổi chụp menu mùa hè 2026 📸',
    errorType: 'PERMANENT',
    errorCode: '100',
    errorMessage: 'Định dạng media không hợp lệ: ảnh vượt quá 8MB hoặc tỷ lệ khung hình không được hỗ trợ.',
    failedAt: '2026-07-12T14:02:00',
  },
  {
    id: 'mock-5',
    scheduleId: 'mock-sch-5',
    contentItemId: 'mock-ci-5',
    platformName: 'INSTAGRAM',
    accountName: '@aima.coffee',
    caption: 'Uống cà phê AIMA mỗi ngày giúp giảm cân và chữa mất ngủ hiệu quả.',
    errorType: 'POLICY_VIOLATION',
    errorCode: '368',
    errorMessage: 'Nội dung vi phạm chính sách quảng cáo y tế: tuyên bố công dụng sức khỏe không có căn cứ.',
    failedAt: '2026-07-11T16:30:00',
  },
  {
    id: 'mock-6',
    scheduleId: 'mock-sch-6',
    contentItemId: null,
    platformName: 'THREADS',
    accountName: '@aima.coffee',
    caption: null,
    errorType: 'TEMPORARY',
    errorCode: '2',
    errorMessage: 'Nền tảng tạm thời không phản hồi (timeout). Bài sẽ được thử lại theo lịch retry.',
    failedAt: '2026-07-11T08:15:00',
  },
  {
    id: 'mock-7',
    scheduleId: 'mock-sch-7',
    contentItemId: 'mock-ci-7',
    platformName: 'FACEBOOK',
    accountName: 'AIMA Coffee House',
    caption: 'Săn deal cuối tuần: mua 1 tặng 1 cho mọi loại trà trái cây 🍊',
    errorType: 'PERMANENT',
    errorCode: '190',
    errorMessage: 'Trang Facebook đã thu hồi quyền đăng bài của ứng dụng. Cần cấp lại quyền khi kết nối.',
    failedAt: '2026-07-10T11:48:00',
  },
  {
    id: 'mock-8',
    scheduleId: 'mock-sch-8',
    contentItemId: 'mock-ci-8',
    platformName: 'INSTAGRAM',
    accountName: '@aima.coffee',
    caption: 'Cam kết hoàn tiền 200% nếu bạn không thấy ngon — đảm bảo tuyệt đối!',
    errorType: 'POLICY_VIOLATION',
    errorCode: '368',
    errorMessage: 'Nội dung vi phạm chính sách quảng cáo: cam kết hoàn tiền phóng đại, dễ gây hiểu lầm cho người dùng.',
    failedAt: '2026-07-09T19:20:00',
  },
  {
    id: 'mock-9',
    scheduleId: 'mock-sch-9',
    contentItemId: 'mock-ci-9',
    platformName: 'THREADS',
    accountName: '@aima.coffee',
    caption: 'Một buổi sáng chậm rãi cùng ly bạc xỉu nóng ☁️',
    errorType: 'TEMPORARY',
    errorCode: '2',
    errorMessage: 'Máy chủ nền tảng trả lỗi tạm thời (service unavailable). Đã thử lại 3 lần nhưng chưa thành công.',
    failedAt: '2026-07-09T06:55:00',
  },
  {
    id: 'mock-10',
    scheduleId: 'mock-sch-10',
    contentItemId: 'mock-ci-10',
    platformName: 'FACEBOOK',
    accountName: 'AIMA Coffee House',
    caption: 'Thuốc bổ từ cà phê: chữa đau đầu, hết stress ngay lập tức!',
    errorType: 'POLICY_VIOLATION',
    errorCode: '368',
    errorMessage: 'Nội dung vi phạm Tiêu chuẩn cộng đồng: gán công dụng y tế cho thực phẩm không có kiểm chứng.',
    failedAt: '2026-07-08T15:40:00',
  },
  {
    id: 'mock-11',
    scheduleId: 'mock-sch-11',
    contentItemId: 'mock-ci-11',
    platformName: 'INSTAGRAM',
    accountName: '@aima.coffee',
    caption: 'Toàn cảnh quán mới tại Quận 3 — hẹn bạn ghé chơi cuối tuần này 🌿',
    errorType: 'PERMANENT',
    errorCode: '100',
    errorMessage: 'Video vượt quá thời lượng cho phép của Reels. Hãy cắt ngắn video rồi đăng lại.',
    failedAt: '2026-07-08T10:05:00',
  },
  {
    id: 'mock-12',
    scheduleId: 'mock-sch-12',
    contentItemId: 'mock-ci-12',
    platformName: 'THREADS',
    accountName: '@aima.coffee',
    caption: 'Poll nhanh: mở cửa tới 23h hay 24h? Vote ngay bên dưới 👇',
    errorType: 'TEMPORARY',
    errorCode: '4',
    errorMessage: 'Ứng dụng chạm ngưỡng rate limit theo giờ của nền tảng. Bài sẽ được thử lại theo lịch retry.',
    failedAt: '2026-07-07T21:30:00',
  },
  {
    id: 'mock-13',
    scheduleId: 'mock-sch-13',
    contentItemId: 'mock-ci-13',
    platformName: 'FACEBOOK',
    accountName: 'AIMA Coffee House',
    caption: 'Giới thiệu blend mới: 100% khách hàng đánh giá 5 sao, ngon nhất Việt Nam.',
    errorType: 'POLICY_VIOLATION',
    errorCode: '368',
    errorMessage: 'Nội dung vi phạm chính sách quảng cáo: tuyên bố "nhất/duy nhất" không kèm bằng chứng xác thực.',
    failedAt: '2026-07-07T09:12:00',
  },
  {
    id: 'mock-14',
    scheduleId: 'mock-sch-14',
    contentItemId: 'mock-ci-14',
    platformName: 'INSTAGRAM',
    accountName: '@aima.coffee',
    caption: 'Behind the scenes: quy trình rang xay tại xưởng AIMA 🔥',
    errorType: 'PERMANENT',
    errorCode: '190',
    errorMessage: 'Access token không còn hợp lệ do tài khoản đổi mật khẩu. Hãy kết nối lại tài khoản Instagram.',
    failedAt: '2026-07-06T17:25:00',
  },
];

/** Toàn bộ mock (bản sao) — trang lọc/phân trang client-side trên danh sách này. */
export function mockFailedPosts(): FailedPost[] {
  return [...MOCK_FAILED_POSTS];
}
